version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: motorrent_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: motorrentdb
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - motorrent_net
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: motorrent_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"     # RabbitMQ server
      - "15672:15672"   # RabbitMQ Management UI
    networks:
      - motorrent_net

volumes:
  postgres_data:
  mongo_data:

networks:
  motorrent_net:
    driver: bridge
